-- ADR-044 — Domaine « Agents immobiliers partenaires »
--
-- Migration PUREMENT ADDITIVE : deux tables neuves, une seule colonne ajoutée
-- à l'existant (`leads.agent_id`). Aucune contrainte durcie, aucun trigger
-- existant modifié.
--
-- ⚠ Ce domaine n'est PAS le domaine mandataire suspendu (ADR-028). Un
-- mandataire est un sous-traitant qui cherche des terrains pour Howner ; un
-- agent immobilier partenaire est une entreprise indépendante qui recommande
-- Howner à sa propre clientèle. Aucune surface mandataire n'est touchée ici.
--
-- ⚠ Ce n'est pas non plus une sixième cible commerciale : un agent n'achète
-- pas un studio, il le prescrit. D'où une table, et non une valeur de plus
-- dans `leads.cible_commerciale`. Décision de Richard, 2026-08-31.

-- ════════════════════════════════════════════════════════════════════════════
-- 1. agents_immo — la fiche partenaire
-- ════════════════════════════════════════════════════════════════════════════
--
-- Les 167 contacts de la liste Brevo `Agents` (id 9) ne sont PAS copiés ici.
-- Brevo reste le fichier de prospection ; cette table ne porte que les agences
-- prises en suivi. La jonction est l'email — d'où son unicité.

create table if not exists public.agents_immo (
  id            uuid primary key default gen_random_uuid(),
  agent_number  bigint generated by default as identity,

  -- ── Identité ──────────────────────────────────────────────────────────────
  -- Pré-remplie depuis les attributs Brevo à la prise en suivi, éditable
  -- ensuite. Ce qui est saisi ici fait foi : Brevo n'écrase jamais la fiche.
  agence        text not null,
  prenom        text,
  nom           text,
  fonction      text,
  -- Clé de rapprochement avec Brevo. `citext` n'est pas installé : l'unicité
  -- porte donc sur un index fonctionnel en minuscules (plus bas), sinon
  -- « Contact@agence.fr » et « contact@agence.fr » cohabiteraient.
  email         text not null,
  tel           text,
  tel_fixe      text,

  -- ── Localisation ──────────────────────────────────────────────────────────
  adresse       text,
  code_postal   text,
  commune       text,
  departement   text,

  -- ── Entreprise ────────────────────────────────────────────────────────────
  siren         text,
  siret         text,
  naf           text,
  site_web      text,
  linkedin      text,

  -- ── Origine ───────────────────────────────────────────────────────────────
  -- D'où vient la ligne. `source_contact` reprend l'attribut Brevo du même nom
  -- (« FNAIM Gironde », « FNAIM Landes ») ; `url_source` la page d'annuaire.
  -- Les conserver permet de répondre à « d'où sort ce contact ? » un an après.
  brevo_contact_id  bigint,
  source_contact    text,
  url_source        text,

  -- ── Suivi (mêmes notions que `leads`, mêmes helpers) ──────────────────────
  -- La contrainte de valeurs vit dans `src/lib/agents.ts`, comme pour les
  -- conseillers : un CHECK figé imposerait une migration à chaque ajout de
  -- statut, et le cycle de partenariat n'est pas stabilisé.
  statut_partenariat  text not null default 'a_contacter',
  responsable         text,
  responsable_at      timestamptz,
  prochain_rappel_at  timestamptz,
  -- Dénormalisés, maintenus par trigger depuis `agent_appels`.
  dernier_appel_at    timestamptz,
  derniere_issue      text,

  -- ── Dernier email (dénormalisé depuis Brevo — ADR-044 §4) ─────────────────
  -- La source reste Brevo : la fiche lit `/v3/smtp/emails` en direct. Ces
  -- colonnes n'existent que pour TRIER la liste — 167 lignes triées sur le
  -- dernier email exigeraient 167 appels API. Alimentées par UN appel global
  -- à `/v3/smtp/statistics/events`, rapproché par adresse.
  -- `dernier_email_sync_at` dit quand la copie a été rafraîchie : sans elle,
  -- une colonne vide ne distingue pas « jamais écrit » de « jamais synchronisé ».
  dernier_email_at        timestamptz,
  dernier_email_sujet     text,
  dernier_email_etat      text,
  dernier_email_sync_at   timestamptz,

  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Un agent = une adresse. C'est la clé qui rapproche la fiche du contact Brevo ;
-- deux fiches pour la même adresse rendraient le vivier incapable de dire ce
-- qui est déjà suivi.
create unique index if not exists agents_immo_email_unique
  on public.agents_immo (lower(email));

create index if not exists agents_immo_statut_idx      on public.agents_immo(statut_partenariat);
create index if not exists agents_immo_responsable_idx on public.agents_immo(responsable);
create index if not exists agents_immo_departement_idx on public.agents_immo(departement);
create index if not exists agents_immo_rappel_idx      on public.agents_immo(prochain_rappel_at)
  where prochain_rappel_at is not null;
create index if not exists agents_immo_dernier_appel_idx on public.agents_immo(dernier_appel_at);
create index if not exists agents_immo_dernier_email_idx on public.agents_immo(dernier_email_at);

alter table public.agents_immo enable row level security;

drop policy if exists "admin_agents_immo_all" on public.agents_immo;
create policy "admin_agents_immo_all" on public.agents_immo
  for all
  using      ((auth.jwt() ->> 'role') = 'admin')
  with check ((auth.jwt() ->> 'role') = 'admin');

-- ════════════════════════════════════════════════════════════════════════════
-- 2. agent_appels — le journal, cloné et non généralisé (ADR-044 §8)
-- ════════════════════════════════════════════════════════════════════════════
--
-- Même forme que `lead_appels`, à dessein. Rendre `lead_appels.lead_id`
-- nullable, poser un CHECK d'exclusivité et réécrire un trigger QUI TOURNE EN
-- PRODUCTION pour accueillir une seconde population, c'est prendre un risque
-- sur le journal existant pour économiser une cinquantaine de lignes de SQL.
--
-- La factorisation utile est côté code, où elle est gratuite : `SENS_APPEL`,
-- `ISSUES_APPEL`, `etatSuivi()` et `urgence()` restent dans `src/lib/crm.ts` et
-- servent les deux domaines.

create table if not exists public.agent_appels (
  id                  uuid primary key default gen_random_uuid(),
  agent_id            uuid not null references public.agents_immo(id) on delete cascade,

  -- 'note' ne compte pas comme un contact : le trigger l'exclut du calcul.
  sens                text not null default 'sortant'
                      check (sens in ('entrant', 'sortant', 'note')),

  issue               text check (issue is null or issue in (
                        'joint', 'repondeur', 'pas_de_reponse',
                        'rappel_demande', 'refus'
                      )),

  note                text,
  duree_min           smallint check (duree_min is null or duree_min >= 0),
  auteur              text,

  prochain_rappel_at  timestamptz,

  -- Date réelle de l'appel, antidatable. Distincte de `created_at`, date de saisie.
  occurred_at         timestamptz not null default now(),
  created_at          timestamptz not null default now()
);

create index if not exists agent_appels_agent_idx
  on public.agent_appels(agent_id, occurred_at desc);

alter table public.agent_appels enable row level security;

drop policy if exists "admin_agent_appels_all" on public.agent_appels;
create policy "admin_agent_appels_all" on public.agent_appels
  for all
  using      ((auth.jwt() ->> 'role') = 'admin')
  with check ((auth.jwt() ->> 'role') = 'admin');

-- ── Trigger : dernier_appel_at + derniere_issue ─────────────────────────────
--
-- Recalcul depuis la source à chaque écriture, jamais d'incrément : une erreur
-- ne peut produire qu'une valeur en retard d'une écriture, pas une valeur
-- durablement fausse.
--
-- ⚠ `security invoker`, jamais `definer` — leçon d'ADR-035 relevée par l'audit
-- Supabase : dans le schéma `public`, une fonction `definer` est exposée en
-- `/rest/v1/rpc/` et devient appelable par un anonyme qui devine un UUID.
--
-- ⚠ L'issue retenue est celle du dernier appel QUI EN PORTE UNE, pas celle du
-- dernier appel tout court : une note ajoutée après coup effacerait sinon le
-- « Répondeur » de la veille. Tri sur `(occurred_at, created_at)` — deux appels
-- saisis à la même date se départagent par ordre de saisie.

create or replace function public.agents_recalc_dernier_appel(p_agent_id uuid)
returns void
language sql
security invoker
set search_path = public
as $$
  update public.agents_immo a
     set dernier_appel_at = (
           select max(x.occurred_at)
             from public.agent_appels x
            where x.agent_id = p_agent_id
              and x.sens in ('entrant', 'sortant')
         ),
         derniere_issue = (
           select x.issue
             from public.agent_appels x
            where x.agent_id = p_agent_id
              and x.issue is not null
            order by x.occurred_at desc, x.created_at desc
            limit 1
         )
   where a.id = p_agent_id;
$$;

create or replace function public.agents_sync_dernier_appel()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Deux appels plutôt qu'un test d'égalité : quand `agent_id` n'a pas changé,
  -- le second recalcul est idempotent ; quand il a changé (entrée déplacée),
  -- les deux fiches sont remises à jour.
  if tg_op <> 'INSERT' then
    perform public.agents_recalc_dernier_appel(old.agent_id);
  end if;
  if tg_op <> 'DELETE' then
    perform public.agents_recalc_dernier_appel(new.agent_id);
  end if;
  return null;
end;
$$;

revoke all on function public.agents_recalc_dernier_appel(uuid) from public, anon, authenticated;
revoke all on function public.agents_sync_dernier_appel()      from public, anon, authenticated;
grant execute on function public.agents_recalc_dernier_appel(uuid) to service_role;

drop trigger if exists trg_agent_appels_sync on public.agent_appels;
create trigger trg_agent_appels_sync
  after insert or update or delete on public.agent_appels
  for each row execute function public.agents_sync_dernier_appel();

-- ── updated_at ──────────────────────────────────────────────────────────────

create or replace function public.agents_immo_touch()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.agents_immo_touch() from public, anon, authenticated;

drop trigger if exists trg_agents_immo_touch on public.agents_immo;
create trigger trg_agents_immo_touch
  before update on public.agents_immo
  for each row execute function public.agents_immo_touch();

-- ════════════════════════════════════════════════════════════════════════════
-- 3. leads.agent_id — l'assiette de la future commission (ADR-044 §5)
-- ════════════════════════════════════════════════════════════════════════════
--
-- Un partenaire ne vaut que par ce qu'il apporte. Cette colonne relie le lead à
-- l'agent qui l'a présenté ; elle alimente l'onglet « Leads apportés » et, le
-- jour où un contrat prévoira une commission, son calcul se lira ici.
-- Reconstituer après coup qui a apporté quoi serait impossible.
--
-- ⚠ SANS RAPPORT avec `mandataire_id` (ADR-028, suspendu) ni avec `responsable`
-- (le conseiller AHF). Trois notions, trois colonnes.
--
-- `on delete set null` : supprimer une fiche partenaire ne doit pas emporter
-- les leads qu'elle a apportés.

alter table public.leads
  add column if not exists agent_id uuid references public.agents_immo(id) on delete set null;

create index if not exists leads_agent_id_idx on public.leads(agent_id)
  where agent_id is not null;

comment on column public.leads.agent_id is
  'Agent immobilier partenaire qui a apporté ce lead (ADR-044). Se lit avec sourcing = ''partenaire''. Ni mandataire_id (ADR-028), ni responsable (conseiller AHF).';
